### ISSUE TITLE
[Question] Publishing to Chrome Web Store?

### ISSUE THREAD

**Issue by ryanbuening** [jaksim/less-distracting-reddit#1]
Hey,

Nice extension. Are you planning on publishing this to the Chrome web store? If not, do you care if I do?

Thanks.

**Comment by ryanbuening** [comment]
So I did find an open source Reddit extension that is published to the Chrome web store: https://github.com/robin-pham/KillFrontPage

**Comment by jaksim** [comment]
Hi,
glad you've found a different extension for your use case. As for publishing this one, it's already been submitted, but isn't approved yet.
